# Generated by Django 4.0.1 on 2022-01-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullname',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='LastName'),
        ),
    ]
